[program:checkpointer]
command=CHECKPOINTER_BINARY_PLACEHOLDER --config CHECKPOINTER_CONFIG_PLACEHOLDER --bind-address 127.0.0.1 --port 42069
user=SERVICE_USER_PLACEHOLDER
autostart=false
autorestart=false
startsecs=3
priority=400
stopasgroup=true
killasgroup=true
stdout_logfile=SUPERVISOR_LOG_DIR_PLACEHOLDER/checkpointer.log
stderr_logfile=SUPERVISOR_LOG_DIR_PLACEHOLDER/checkpointer.err
stdout_logfile_maxbytes=200MB
stderr_logfile_maxbytes=200MB
stdout_logfile_backups=5
stderr_logfile_backups=5
