[program:summit-deposit-rpc]
command=SUMMIT_BINARY_PLACEHOLDER
    deposit-rpc
    --genesis-path GENESIS_PATH_PLACEHOLDER
    --key-store-path SUMMIT_KEYS_DIR_PLACEHOLDER
    --port 3031
user=SERVICE_USER_PLACEHOLDER
autostart=false
autorestart=false
startsecs=1
priority=100
stopasgroup=true
killasgroup=true
stdout_logfile=SUPERVISOR_LOG_DIR_PLACEHOLDER/summit-deposit-rpc.log
stderr_logfile=SUPERVISOR_LOG_DIR_PLACEHOLDER/summit-deposit-rpc.err
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
stdout_logfile_backups=2
stderr_logfile_backups=2
