[program:summit-observer-checkpoint]
command=SUMMIT_CHECKPOINT_RUNNER_PLACEHOLDER
    --config CHECKPOINT_START_CONFIG_PLACEHOLDER
    --lock-file OBSERVER_STORE_DIR_PLACEHOLDER/.summit-process.lock
    --
    SUMMIT_BINARY_PLACEHOLDER
    run
    --observer OBSERVER_INDEX_PLACEHOLDER
    --ip OBSERVER_PUBLIC_ADDRESS_PLACEHOLDER
    --port OBSERVER_P2P_PORT_PLACEHOLDER
    --genesis-path GENESIS_PATH_PLACEHOLDER
    --key-store-path SUMMIT_KEYS_DIR_PLACEHOLDER
    --store-path OBSERVER_STORE_DIR_PLACEHOLDER
    --engine-ipc-path /tmp/reth_engine_api.ipc
    --rpc-ip 127.0.0.1
    --rpc-port 3030
    --admin-rpc-port 3031
    --prom-ip 127.0.0.1
    --prom-port 9090
BOOTSTRAPPERS_ARGUMENT_PLACEHOLDER
    --critical-log-dir OBSERVER_CRITICAL_LOG_DIR_PLACEHOLDER
user=SERVICE_USER_PLACEHOLDER
autostart=false
autorestart=false
startsecs=3
priority=300
stopasgroup=true
killasgroup=true
stdout_logfile=SUPERVISOR_LOG_DIR_PLACEHOLDER/summit-observer-checkpoint.log
stderr_logfile=SUPERVISOR_LOG_DIR_PLACEHOLDER/summit-observer-checkpoint.err
stdout_logfile_maxbytes=200MB
stderr_logfile_maxbytes=200MB
stdout_logfile_backups=5
stderr_logfile_backups=5
