[program:custodian]
command=CUSTODIAN_BINARY_PLACEHOLDER
    --socket CUSTODIAN_SOCKET_PLACEHOLDER
    --root-key-file CUSTODIAN_ROOT_KEY_PLACEHOLDER
    --delivery-dir CUSTODIAN_DELIVERY_DIR_PLACEHOLDER
    --council-listen COUNCIL_LISTEN_PLACEHOLDER
    --council-address COUNCIL_ADDRESS_PLACEHOLDER
    --chain-id CUSTODIAN_CHAIN_ID_PLACEHOLDER
    --observer OBSERVER_INDEX_PLACEHOLDER
    --parent-custodian PARENT_CUSTODIAN_PLACEHOLDER
    --summit-key-dir SUMMIT_KEYS_DIR_PLACEHOLDER
    --allow SERVICE_USER_PLACEHOLDER:tx-io,rng
user=SERVICE_USER_PLACEHOLDER
autostart=false
autorestart=false
startsecs=3
priority=100
stopasgroup=true
killasgroup=true
stdout_logfile=SUPERVISOR_LOG_DIR_PLACEHOLDER/custodian.log
stderr_logfile=SUPERVISOR_LOG_DIR_PLACEHOLDER/custodian.err
stdout_logfile_maxbytes=200MB
stderr_logfile_maxbytes=200MB
stdout_logfile_backups=5
stderr_logfile_backups=5
