[program:prometheus-agent]
command=BINARY_PLACEHOLDER
    --agent
    --config.file=/etc/seismic/prometheus-agent/prometheus.yml
    --storage.agent.path=DATA_PLACEHOLDER
    --storage.agent.retention.min-time=5m
    --storage.agent.retention.max-time=6h
    --storage.agent.wal-compression
    --storage.remote.flush-deadline=30s
    --web.listen-address=127.0.0.1:9091
user=seismic-prometheus
umask=0027
autostart=false
autorestart=true
startsecs=3
startretries=5
priority=400
stopwaitsecs=40
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/seismic-prometheus-agent/agent.log
stderr_logfile=/var/log/seismic-prometheus-agent/agent.err
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
stdout_logfile_backups=3
stderr_logfile_backups=3
