[program:summit]
command=SUMMIT_BINARY_PLACEHOLDER
    run
    --genesis-path GENESIS_PATH_PLACEHOLDER
    --key-store-path SUMMIT_KEYS_DIR_PLACEHOLDER
    --store-path SUMMIT_DATA_DIR_PLACEHOLDER
    --rpc-ip SUMMIT_RPC_BIND_PLACEHOLDER
    --prom-ip SUMMIT_PROM_BIND_PLACEHOLDER
user=SERVICE_USER_PLACEHOLDER
autostart=false
autorestart=false
startsecs=3
priority=300
stopasgroup=true
killasgroup=true
stdout_logfile=SUPERVISOR_LOG_DIR_PLACEHOLDER/summit.log
stderr_logfile=SUPERVISOR_LOG_DIR_PLACEHOLDER/summit.err
stdout_logfile_maxbytes=200MB
stderr_logfile_maxbytes=200MB
stdout_logfile_backups=5
stderr_logfile_backups=5
