[program:reth]
command=RETH_BINARY_PLACEHOLDER
    node -vvv
    --p2p-secret-key RETH_P2P_KEY_PLACEHOLDER
    --http
    --http.addr RETH_RPC_BIND_PLACEHOLDER
    --http.port 8545
    --http.api eth,net,web3
    --http.corsdomain *
    --ws
    --ws.addr RETH_RPC_BIND_PLACEHOLDER
    --ws.port 8546
    --ws.api eth,net,web3
    --ws.origins *
    --port 30303
    --metrics 9001
    --datadir RETH_DATA_DIR_PLACEHOLDER
    --ipcdisable
    --auth-ipc
    --auth-ipc.path /tmp/reth_engine_api.ipc
    --rpc.enable-storage-apis
    PURPOSE_KEYS_ARGUMENTS_PLACEHOLDER
    --disable-discv4-discovery
    --disable-dns-discovery
    --enable-discv5-discovery
    --discovery.v5.port 30303
    BOOTNODE_ARGUMENT_PLACEHOLDER
    --ops.enable
    --ops.addr 127.0.0.1
    --ops.port 8552
user=SERVICE_USER_PLACEHOLDER
autostart=false
autorestart=false
startsecs=10
priority=200
stopasgroup=true
killasgroup=true
stdout_logfile=SUPERVISOR_LOG_DIR_PLACEHOLDER/reth.log
stderr_logfile=SUPERVISOR_LOG_DIR_PLACEHOLDER/reth.err
stdout_logfile_maxbytes=200MB
stderr_logfile_maxbytes=200MB
stdout_logfile_backups=5
stderr_logfile_backups=5

[program:summit]
command=SUMMIT_BINARY_PLACEHOLDER
    run
    --genesis-path GENESIS_PATH_PLACEHOLDER
    --key-store-path SUMMIT_KEYS_DIR_PLACEHOLDER
    --store-path SUMMIT_DATA_DIR_PLACEHOLDER
    --rpc-ip SUMMIT_RPC_BIND_PLACEHOLDER
    --prom-ip SUMMIT_PROM_BIND_PLACEHOLDER
user=SERVICE_USER_PLACEHOLDER
autostart=false
autorestart=false
startsecs=3
priority=300
stopasgroup=true
killasgroup=true
stdout_logfile=SUPERVISOR_LOG_DIR_PLACEHOLDER/summit.log
stderr_logfile=SUPERVISOR_LOG_DIR_PLACEHOLDER/summit.err
stdout_logfile_maxbytes=200MB
stderr_logfile_maxbytes=200MB
stdout_logfile_backups=5
stderr_logfile_backups=5
